- name: Enable fgfm-peercert-withoutsn on FortiManager based on version conditions
  hosts: fortimanager
  gather_facts: no
  collections:
    - fortinet.fortimanager

  vars:
    min_version_72: "7.2.5"
    min_version_74: "7.4.3"

  tasks:
    - name: Get FortiManager system information
      fmgr_fact:
        facts:
          - system/status
      register: result

    - name: Check if FortiManager version meets the conditions
      set_fact:
        version: "{{ result.ansible_facts['system_status']['version'] }}"
        is_target_version: >-
          {{
            (version.startswith('7.2') and version_compare(version, min_version_72, '>=')) or
            (version.startswith('7.4') and version_compare(version, min_version_74, '>='))
          }}

    - name: Enable fgfm-peercert-withoutsn if version matches criteria
      fmgr_system_global:
        bypass_validation: yes
        system_global:
          fgfm-peercert-withoutsn: "enable"
      when: is_target_version
      register: set_config

    - name: Display result
      debug:
        msg: "Configuration set successfully: {{ set_config }}"
      when: set_config is defined
