- name: Retrieve FortiManager System Settings
  hosts: fortimanager
  gather_facts: no
  vars:
  
  tasks:
    - name: get system status
      uri:
        url: "{{ fmg_api_url }}"
        method: POST
        body_format: json
        headers:
          Authorization: "{{ auth }}"
        body:
          method: "get"
          params:
            - url: "/sys/status"

      register: auth_response

    - name: Print authenticated response
      debug:
        var: auth_response.content
