---
- name: FortiManager API interaction to get system status
  hosts: localhost
  tasks:

    - name: Login to FortiManager
      uri:
        url: "{{ fmg_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "method": "exec",
            "params": [
              {
                "url": "/sys/login/user",
                "data": {
                  "user": "{{ user }}",
                  "passwd": "{{ pass }}"
                }
              }
            ],
            "id": 1
          }
        body_format: json
        validate_certs: no
        return_content: yes
      register: login_response

    - name: Extract session ID from login response
      set_fact:
        session_id: "{{ login_response.json.session }}"  # Captures session token

    - name: Get system status from FortiManager
      uri:
        url: "{{ fmg_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "method": "get",
            "params": [
              {
                "url": "/sys/status",
                "session": "{{ session_id }}"
              }
            ],
            "id": 1
          }
        body_format: json
        validate_certs: no
        return_content: yes
      register: status_response

    - name: Display system status
      debug:
        var: status_response.json

    - name: Log out from FortiManager
      uri:
        url: "{{ fmg_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "method": "exec",
            "params": [
              {
                "url": "/sys/logout",
                "session": "{{ session_id }}"
              }
            ],
            "id": 1
          }
        body_format: json
        validate_certs: no
        return_content: yes
